export enum ElectronStoreKeys {
	AppLanguage = 'appLanguage',
	IsNotFirstTimeAppStart = 'isNotFirstTimeAppStart',
	Theme = 'theme',
	UIStyle = 'uiStyle',
	TrustedDeviceIds = 'trustedDeviceIds',
	DeviceAliasOverrides = 'deviceAliasOverrides',
	AutoStartOnLogin = 'autoStartOnLogin',
	PreventAccidentalQuit = 'preventAccidentalQuit',
	CustomServerPort = 'customServerPort',
	NetworkInterfaceIP = 'networkInterfaceIP',
	BrandName = 'brandName',
	BannedIPs = 'bannedIPs',
	ConnectionPassword = 'connectionPassword',
	UseSystemTray = 'useSystemTray',
	LastDesktopCapturerSourceID = 'lastDesktopCapturerSourceID',
}
